name: WinterHub Solver

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  solve:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run solver
        env:
          WH_API_KEY:   ${{ secrets.WH_API_KEY }}
          WH_COOKIES_1: ${{ secrets.WH_COOKIES_1 }}
          WH_COOKIES_2: ${{ secrets.WH_COOKIES_2 }}
          WH_COOKIES_3: ${{ secrets.WH_COOKIES_3 }}
          WH_COOKIES_4: ${{ secrets.WH_COOKIES_4 }}
          PLACE_ID:     ${{ vars.PLACE_ID }}
          DELAY_COOKIE: ${{ vars.DELAY_COOKIE }}
          DELAY_LOOP:   ${{ vars.DELAY_LOOP }}
          SOLVE_POW:    ${{ vars.SOLVE_POW }}
          SOLVE_POS:    ${{ vars.SOLVE_POS }}
          SOLVE_CAP:    ${{ vars.SOLVE_CAP }}
        run: python solver.py
